### ISSUE TITLE
This project should be moved/added to Blazor.Extensions

### ISSUE THREAD

**Issue by bmsantos** [philipblaquiere/Blazor.Payments#1]
Pretty sweet project you have here. May make use of it in [Bionic](https://github.com/BionicFramework).

@philipblaquiere, you should consider making this a [Blazor.Extension](https://github.com/BlazorExtensions)

**Comment by philipblaquiere** [comment]
Thanks! I proposed its addition to Blazor.Extensions.

**Comment by bmsantos** [comment]
Thanks.
